# Security audit configuration for cargo audit
#
# This file ignores specific security advisories that don't affect our usage

[advisories]
# Database dependencies removed - MCP servers should be simple and stateless
ignore = [
    "RUSTSEC-2024-0436",  # paste crate unmaintained warning - indirect dependency from amari
]